### ISSUE TITLE
Adding support for folders (directories)

### ISSUE THREAD

**Issue by BrianHoldsworth** [feenkcom/file-matcher-rs#1]
I wanted to use `FileNamed::wildmatch()` to see if a matching directory exists in the given path. Alas, this does not work because of the implementation for `readable_files_in_folder`.

 I can see this would be nice when you only want files, since it saves you having to filter out folder names in your own code. But for my use-case, a flag, or an alternate type (`FolderNamed`?), seems like the only way to make it useful.

**Comment by syrel** [comment]
Hey @BrianHoldsworth
Thank you very much for the issue 👍 Indeed, `FolderNamed::*` is a way to go!
Will add it in the next release

**Comment by syrel** [comment]
In the version `0.5.0` it is now possible to `find()` or directly check if a folder `exists()`.

```rust
FolderNamed::wildmatch("cat*")
    .within("tests/assets")
    .exists()?
```
